### ISSUE TITLE
cookie:appid=问题

### ISSUE THREAD

**Issue by luwei0711** [niefy/wx-client#3]
c.g.n.c.exception.RRExceptionHandler     : Missing cookie 'appid' for method parameter of type String
跨域问题，cookie丢失，手动设置报
w3c规定，当请求的header匹配以下不安全字符时，将被终止
  Accept-Charset
  Accept-Encoding
  Connection
  Content-Length
  Cookie
  Cookie2
  Content-Transfer-Encoding
  Date
  Expect
  Host
  Keep-Alive
  Referer
  TE
  Trailer
  Transfer-Encoding
  Upgrade
  User-Agent
  Via
，所以一直报错：fly.min.js:1 Refused to set unsafe header "Cookie"
wx-client部署问题

**Comment by luwei0711** [comment]
c.g.n.c.exception.RRExceptionHandler     : Missing cookie 'appid' for method parameter of type String

**Comment by niefy** [comment]
请按开发环境或生产环境文档（两个环境处理方式不同），不要跨域请求
